import distutils.sysconfig
import os
import sys

PYTHON_LIBPATH = distutils.sysconfig.get_python_lib()
PYTHON_INCPATH = distutils.sysconfig.get_python_inc()
PYTHON_LIBRARY = "python" + sys.version[:3]

cythonBuilder = Builder(action ='cython $SOURCE',
                        suffix = '.c',
                        src_suffix = '.pyx')

env = Environment(ENV      =   os.environ,
                  BUILDERS = {'Py2C':cythonBuilder})

env.Py2C('c1.c', 'c1.pyx')