#!python
# coding=utf-8
"""Setup for testing, building, distributing and installing the 'Pyramid'-package"""

import os
import subprocess
import itertools
from setuptools import setup
from setuptools.config import read_configuration


def git_version():
    '''Get current git revision.'''
    try:
        git_rev = subprocess.check_output(['git', 'rev-parse', 'HEAD']).strip().decode()
    except Exception:
        git_rev = "???"
    return git_rev


def write_version_py(version, git_version, filename='pyramid/version.py'):
    '''Write version.py file.'''
    version_string = '# -*- coding: utf-8 -*-\n' + \
                     '""""This file was automatically generated by `setup.py`"""\n' + \
                     f'version = "{version}"\n' + \
                     f'git_revision = "{git_version}"\n'
    with open(os.path.join(os.path.dirname(__file__), filename), 'w') as vfile:
        vfile.write(version_string)


# Read setup.cfg (setup() would auto-read it, but we want to read the version and modify it here):
conf_dict = read_configuration('setup.cfg')
metadata_dict = conf_dict['metadata']
options_dict = conf_dict['options']

# Read version and write to version.py:
version = metadata_dict['version']
write_version_py(version, git_version())

# Add 'full' convenience option to extras_require for full install: python setup.py install .[full]
full_list = list(itertools.chain(*list(options_dict['extras_require'].values())))
options_dict['extras_require']['full'] = full_list

# Run setup:
setup(**metadata_dict, **options_dict)  # TODO: Is this overwritten by setup.cfg again?


# TODO: Currently does not work, find out why!

# TODO: HOW TO GET JUTIL???

# TODO: Also create conda recipe!
# TODO: Handle extras via metapackage (depends on pyramid-base that holds the core code and extras?)
# TODO: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html
